### ISSUE TITLE
Maybe a CORS issue?

### ISSUE THREAD

**Issue by micahwierenga** [den-wdi-2/project-4#11]
I'm getting an error that starts with this and only one stackoverflow sort of addresses it:

Possibly unhandled rejection: {"data":"Cannot POST /api/user\n","status":404,"config":{"method":"POST","transformRequest":[null],"transformResponse":

http://stackoverflow.com/questions/41710275/how-to-setup-express-routes-separate-from-main-file

**Comment by ZebGirouard** [comment]
Needed to include routes in server.js.  Looking good now.
