### ISSUE TITLE
Getting an id non-null error

### ISSUE THREAD

**Issue by micahwierenga** [den-wdi-2/project-4#13]
I've been trying to solve this error for a couple hours with no luck:

Unhandled rejection SequelizeDatabaseError: null value in column "id" violates not-null constraint

https://github.com/dresende/node-orm2/issues/391

https://github.com/sequelize/sequelize/issues/4400

http://stackoverflow.com/questions/33662670/error-null-value-in-column-id-violates-not-null-constraint-in-sequelize

https://github.com/sequelize/sequelize/issues/925

https://github.com/sequelize/sequelize/issues/3247

**Comment by ZebGirouard** [comment]
Ah, the old "User" should actually be "Pledge" issue.
