### ISSUE TITLE
Ionic: server to front communication

### ISSUE THREAD

**Issue by git-clay** [den-wdi-2/project-4#2]
If i use localhost, I am able to access my backend and send an external http request to an api. However, using ionic lab I am unable to access the backend functions.

I went through the legacy code but it is in python and hard to convert over to nodejs.

I also went through https://ionicframework.com docs.

I do not know anyone that is working in ionic for project 4. I don't need much on this just a direction to go in. Thanks

**Comment by ZebGirouard** [comment]
Talked to Clay, and advised him to just set up a node back-end separate from Ionic.
