### ISSUE TITLE
finishing up google sign-in

### ISSUE THREAD

**Issue by larrykraus** [den-wdi-2/project-4#6]
I'm working through a tutorial to get google sign in. I'm stuck on one of the last steps...

https://developers.google.com/identity/sign-in/web/backend-auth

https://developers.google.com/api-client-library/php/guide/aaa_idtoken

I talked with Brian regarding this issue and I'm still stuck

**Comment by ZebGirouard** [comment]
Looks like step 4 is a nice-to-have and not too well-documented.  I'd skip it for now, and revisit after presentations to increase security.
